### ISSUE TITLE
inference problem

### ISSUE THREAD

**Issue by heyuton** [RPM-Robotics-Lab/sRGB-TIR#15]
hello, I run this command on Windows:
python inference_batch.py --input_folder ./input --output_folder ./output --checkpoint ./pretrained/translatio
n_weights.pt --a2b 0 --seed 1234 --num_style 5 --synchronized --output_only --config configs/tir2rgb_folder.yaml

but i got this error:
RuntimeError: DataLoader worker (pid(s) 21824, 27008, 3960, 11708) exited unexpectedly

what is the reason for this?how can I fix this?

**Comment by ckavak** [comment]
Hello, did you found any solution ?
